# Generated by Django 3.1.8 on 2022-04-06 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cusername', models.CharField(max_length=10, unique=True, verbose_name='cusername')),
                ('cemail', models.EmailField(max_length=254, unique=True, verbose_name='cemail address')),
                ('cfname', models.CharField(max_length=200, null=True, verbose_name='cfname')),
                ('cmname', models.CharField(max_length=20, null=True)),
                ('clname', models.CharField(max_length=20, null=True)),
                ('cgender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('cmobileno', models.CharField(max_length=50, null=True)),
                ('caddress1', models.CharField(max_length=20, null=True)),
                ('caddress2', models.CharField(max_length=20, null=True)),
                ('ccity', models.CharField(max_length=20, null=True)),
                ('cstate', models.CharField(max_length=20, null=True)),
                ('ccountry', models.CharField(max_length=20, null=True)),
                ('cpin', models.CharField(max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=100, null=True, unique=True)),
                ('hotelimg', models.ImageField(null=True, upload_to='images/')),
                ('hoteltype', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, null=True, unique=True)),
                ('days', models.IntegerField(null=True)),
                ('nights', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('locationimg', models.ImageField(blank=True, upload_to='images/')),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('day1', models.CharField(max_length=200, null=True)),
                ('day1_desc', models.CharField(max_length=1000, null=True)),
                ('day2', models.CharField(max_length=200, null=True)),
                ('day2_desc', models.CharField(max_length=1000, null=True)),
                ('day3', models.CharField(max_length=200, null=True)),
                ('day3_desc', models.CharField(max_length=1000, null=True)),
                ('day4', models.CharField(max_length=200, null=True)),
                ('day4_desc', models.CharField(max_length=1000, null=True)),
                ('day5', models.CharField(max_length=200, null=True)),
                ('day5_desc', models.CharField(max_length=1000, null=True)),
                ('day6', models.CharField(max_length=200, null=True)),
                ('day6_desc', models.CharField(max_length=1000, null=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='TripReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('tripprice', models.FloatField(null=True)),
                ('person', models.IntegerField(null=True)),
                ('totalprice', models.FloatField(null=True)),
                ('remaining_amount', models.IntegerField(null=True)),
                ('children', models.IntegerField(null=True)),
                ('trip_status', models.IntegerField(default=1, null=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.trips')),
            ],
        ),
        migrations.CreateModel(
            name='RemaningReservationPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.IntegerField(null=True)),
                ('paymentmethod', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.trips')),
            ],
        ),
    ]
