# Generated by Django 3.1.8 on 2022-04-06 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_auto_20220406_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plocation', models.CharField(max_length=100, null=True, unique=True)),
                ('pdays', models.IntegerField(null=True)),
                ('pnights', models.IntegerField(null=True)),
                ('pprice', models.FloatField(null=True)),
                ('plocationimg', models.ImageField(blank=True, upload_to='images/')),
                ('pfrom_date', models.DateField(null=True)),
                ('pto_date', models.DateField(null=True)),
                ('pday1', models.CharField(max_length=200, null=True)),
                ('pday1_desc', models.CharField(max_length=1000, null=True)),
                ('pday2', models.CharField(max_length=200, null=True)),
                ('pday2_desc', models.CharField(max_length=1000, null=True)),
                ('pday3', models.CharField(max_length=200, null=True)),
                ('pday3_desc', models.CharField(max_length=1000, null=True)),
                ('pday4', models.CharField(max_length=200, null=True)),
                ('pday4_desc', models.CharField(max_length=1000, null=True)),
                ('pday5', models.CharField(max_length=200, null=True)),
                ('pday5_desc', models.CharField(max_length=1000, null=True)),
                ('pday6', models.CharField(max_length=200, null=True)),
                ('pday6_desc', models.CharField(max_length=1000, null=True)),
                ('pstatus', models.IntegerField(default=1, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('pcreated_at', models.DateTimeField(auto_now_add=True)),
                ('pupdated_at', models.DateTimeField(auto_now=True)),
                ('pcreated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.services')),
            ],
        ),
        migrations.AlterField(
            model_name='remaningreservationpayment',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.package'),
        ),
        migrations.AlterField(
            model_name='tripreservation',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.package'),
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
