# Generated by Django 3.1.8 on 2022-04-06 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_auto_20220406_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcname', models.CharField(max_length=100, null=True)),
                ('bfrom_date', models.DateField(null=True)),
                ('bto_date', models.DateField(null=True)),
                ('btripprice', models.FloatField(null=True)),
                ('bperson', models.IntegerField(null=True)),
                ('btotalprice', models.FloatField(null=True)),
                ('bremaining_amount', models.IntegerField(null=True)),
                ('bchildren', models.IntegerField(null=True)),
                ('btrip_status', models.IntegerField(default=1, null=True)),
                ('bstatus', models.IntegerField(default=1, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('bcreated_at', models.DateTimeField(auto_now_add=True)),
                ('bupdated_at', models.DateTimeField(auto_now=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.package')),
            ],
        ),
        migrations.DeleteModel(
            name='TripReservation',
        ),
    ]
