# Generated by Django 3.1.8 on 2022-04-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_auto_20220406_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='desc',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
