# Generated by Django 3.1.8 on 2022-04-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_services_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='desc',
            new_name='sdesc',
        ),
    ]
